linters:
  enable:
    - errname
    - goconst
    - gocyclo
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - zerologlint

linters-settings:
  staticcheck:
    checks:
      - all

issues:
  exclude-dirs:
    - third_party
    - builtin
    - examples
